# Generated by Django 3.2.3 on 2021-06-02 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210602_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 2, 20, 59, 52, 170617, tzinfo=utc)),
        ),
    ]
