# Generated by Django 3.2.6 on 2021-08-10 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating must be 1 or greater !!'), django.core.validators.MaxValueValidator(5, message='Max rating 5 is allowed !!')]),
        ),
    ]
